# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ngrpc.proto\"0\n\x0epublishRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t\"\x18\n\x05reply\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1e\n\rbrowseRequest\x12\r\n\x05topic\x18\x01 \x01(\t\":\n\nsubRequest\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x10\n\x08\x63lientId\x18\x02 \x01(\t\x12\x0b\n\x03TTL\x18\x03 \x01(\x05\x32y\n\x06Pubsub\x12$\n\x07publish\x12\x0f.publishRequest\x1a\x06.reply\"\x00\x12$\n\x06\x62rowse\x12\x0e.browseRequest\x1a\x06.reply\"\x00\x30\x01\x12#\n\x08subcribe\x12\x0b.subRequest\x1a\x06.reply\"\x00\x30\x01\x62\x06proto3'
)




_PUBLISHREQUEST = _descriptor.Descriptor(
  name='publishRequest',
  full_name='publishRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='publishRequest.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='context', full_name='publishRequest.context', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=62,
)


_REPLY = _descriptor.Descriptor(
  name='reply',
  full_name='reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='reply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=88,
)


_BROWSEREQUEST = _descriptor.Descriptor(
  name='browseRequest',
  full_name='browseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='browseRequest.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=120,
)


_SUBREQUEST = _descriptor.Descriptor(
  name='subRequest',
  full_name='subRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='subRequest.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clientId', full_name='subRequest.clientId', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='TTL', full_name='subRequest.TTL', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=180,
)

DESCRIPTOR.message_types_by_name['publishRequest'] = _PUBLISHREQUEST
DESCRIPTOR.message_types_by_name['reply'] = _REPLY
DESCRIPTOR.message_types_by_name['browseRequest'] = _BROWSEREQUEST
DESCRIPTOR.message_types_by_name['subRequest'] = _SUBREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

publishRequest = _reflection.GeneratedProtocolMessageType('publishRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUBLISHREQUEST,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:publishRequest)
  })
_sym_db.RegisterMessage(publishRequest)

reply = _reflection.GeneratedProtocolMessageType('reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:reply)
  })
_sym_db.RegisterMessage(reply)

browseRequest = _reflection.GeneratedProtocolMessageType('browseRequest', (_message.Message,), {
  'DESCRIPTOR' : _BROWSEREQUEST,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:browseRequest)
  })
_sym_db.RegisterMessage(browseRequest)

subRequest = _reflection.GeneratedProtocolMessageType('subRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBREQUEST,
  '__module__' : 'grpc_pb2'
  # @@protoc_insertion_point(class_scope:subRequest)
  })
_sym_db.RegisterMessage(subRequest)



_PUBSUB = _descriptor.ServiceDescriptor(
  name='Pubsub',
  full_name='Pubsub',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=182,
  serialized_end=303,
  methods=[
  _descriptor.MethodDescriptor(
    name='publish',
    full_name='Pubsub.publish',
    index=0,
    containing_service=None,
    input_type=_PUBLISHREQUEST,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='browse',
    full_name='Pubsub.browse',
    index=1,
    containing_service=None,
    input_type=_BROWSEREQUEST,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='subcribe',
    full_name='Pubsub.subcribe',
    index=2,
    containing_service=None,
    input_type=_SUBREQUEST,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PUBSUB)

DESCRIPTOR.services_by_name['Pubsub'] = _PUBSUB

# @@protoc_insertion_point(module_scope)
